<!-- <link href="../../../resources/custom/print_format.css" media="print" rel="stylesheet" /> -->
<style type="text/css">
  @page {
    size:letter;
    margin-top: 0.7in; 
    margin-left: 0.7in;
    margin-right: 0.7in;
    margin-bottom: 0.7in;
   
  }
  hr {
     border: none; 
     border-bottom: 1px solid black;
  }
  table {
    border-collapse: collapse;
  }

  table, th, td {
    border: 1px solid black;
  }

  #rlogo {
    margin-left: 290px;
    width: 100px;
  }

</style>


<div style="display: none">

  <div id="membership" class="panel-body" style="color: black">
     <!-- begin panel-body -->
     <!--For Details-->
     
     <!--For Details-->
     <div class="panel" style="font-family: arial;">
        <!-- <p style="font-size: 14px; text-align: center">
           Republic of the Philippines<br>
           Province of Batangas<br>
           Municipality of Tuy<br>
        </p> -->
        <p><img id="rlogo" src="../../../resources/images/nvyc.png"></p>
        <p style="font-size: 16px; font-weight:bold; text-align: center; margin-top: 20px; margin-bottom: 40px">NATIONAL YOUTH VOLUNTEERS COALITION</p>
        <table>
          <tr>
            <td style="width: 480px;border-color: white">
              Date Created: <?php date_default_timezone_set('Asia/Manila'); echo date('F d, Y')?>
            </td>
            <td style="width: 380px; text-align: right;border-color: white">
              Report No: MEM<?php date_default_timezone_set('Asia/Manila'); echo date('Ymd')?>
            </td>
          </tr>
        </table>
        <hr>
        <p style="font-size: 19px; font-weight:bold; text-align: center; margin-top: 20px">REPORT ON PAID FOR MEMBERSHIP</p>
        <hr>

        <p style="font-size: 16px; text-align: justify">
          <b>Report Description:</b><br><br>
           &nbsp;&nbsp;&nbsp;
           This report contains the details of all paid for membership through bank.
           <br>
           &nbsp;&nbsp;&nbsp;
           Details in this report may be filtered according to the specifications and preferences set by the report generator.
        </p>
         <p style="font-size: 16px; text-align: justify">
          <b>Table Description:</b><br><br>
           &nbsp;&nbsp;&nbsp;
           The table contains the following fields: expense, amount, purpose, and date.
           <br>

        </p>
        <table id="data-table" class="table table-striped table-bordered" style="width: 100%">
            <thead>
            <tr>
                <th>Expense</th>
                <th>Amount</th>
                <th>Purpose</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>

          <?php
            $query = "SELECT DISTINCT * FROM ems_t_expenditures WHERE te_status = 1";

                                        $runquery = mysqli_query($connection, $query);

                                        while ($row = mysqli_fetch_assoc($runquery)){

                                          $data_expense = $row['te_expense'];
                                          $data_amount = $row['te_amount'];
                                          $data_purpose = $row['te_purpose'];
                                          $data_date = $row['te_date'];
                                          $dataexeid = $row['te_expenditure_id'];

                                          echo "<tr>
                                                <td>".$data_expense."</td>
                                                <td>".$data_amount."</td>
                                                <td>".$data_purpose."</td>
                                                <td>".$data_date."</td>
                                              </tr>
                                             ";
                                        }

          ?>
        </tbody>
         
        </table>
        <hr>
        <br>
        <p style="font-size: 15px; margin-top:30px; margin-bottom: 20px">
          Report Generated By:<br><br><br>
          <i>Sherie Mae Remo</i> <br>
          <i>Treasurer</i>
        </p>
     </div>
     <!-- end panel-body -->
  </div>
</div>