<!-- <link href="../../../resources/custom/print_format.css" media="print" rel="stylesheet" /> -->
<style type="text/css">
  @page {
    size:letter;
    margin-top: 0.7in; 
    margin-left: 0.7in;
    margin-right: 0.7in;
    margin-bottom: 0.7in;
   
  }
  hr {
     border: none; 
     border-bottom: 1px solid black;
  }
  table {
    border-collapse: collapse;
  }

  table, th, td {
    border: 1px solid black;
  }

  #rlogo {
    margin-left: 290px;
    width: 100px;
  }
</style>


<div style="display: none">
  <div id="demo" class="panel-body" style="color: black">
     <!-- begin panel-body -->
     <!--For Details-->
     
     <!--For Details-->
     <div class="panel" style="font-family: arial;">
        <!-- <p style="font-size: 14px; text-align: center">
           Republic of the Philippines<br>
           Province of Batangas<br>
           Municipality of Tuy<br>
        </p> -->
        <p><img id="rlogo"></p>
        <p style="font-size: 16px; font-weight:bold; text-align: center; margin-top: 20px; margin-bottom: 40px">NATIONAL YOUTH VOLUNTEERS COALITION</p>
        <table>
          <tr>
            <td style="width: 480px;border-color: white">
              Date Created: <?php echo date('F d, Y')?>
            </td>
            <td style="width: 380px; text-align: right;border-color: white">
              Report No: EVENT<?php echo date('Ymd')?>
            </td>
          </tr>
        </table>
        <hr>
        <p style="font-size: 19px; font-weight:bold; text-align: center; margin-top: 20px">REPORT ON CONDUCTED EVENTS</p>
        <hr>

        <p style="font-size: 16px; text-align: justify">
          <b>Report Description:</b><br><br>
           &nbsp;&nbsp;&nbsp;
           This report contains the details of conducted events.
           <br>
           <!-- &nbsp;&nbsp;&nbsp;
           Details in this report may be filtered according to the specifications and preferences set by the report generator. -->
        </p>
         <p style="font-size: 16px; text-align: justify">
          <b>Table Description:</b><br><br>
           &nbsp;&nbsp;&nbsp;
           The table contains the following fields: event name, description, event type, start date, end date.
           <br>

        </p>
        <table id="data-table" class="table table-striped table-bordered" style="width: 100%">
                                    <thead>
                                        <tr>
                                            <th>Event Name</th>
                                            <th>Description</th>
                                            <th>Event Type</th>
                                            <th>Start Date</th>
                                            <th>End Date</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php

                                        $query = "SELECT * FROM ems_r_event INNER JOIN ems_r_event_type ON ems_r_event.re_etype_id = ems_r_event_type.ret_etype_id  WHERE re_event_status = 1";

                                        $runquery = mysqli_query($connection, $query);

                                        while ($row = mysqli_fetch_assoc($runquery)){

                                          $data_event_name = $row['re_event_name'];
                                          $data_event_desc = $row['re_event_description'];
                                          $data_event_type = $row['ret_etype_name'];
                                          $data_start_date = $row['re_event_startdate'];
                                          $data_end_date = $row['re_event_enddate'];
                                          $dataeventid = $row['re_event_id'];

                                          echo "<tr>
                                              <td>".$data_event_name."</td>
                                              <td>".$data_event_desc."</td>
                                              <td>".$data_event_type."</td>
                                              <td>".$data_start_date."</td>
                                              <td>".$data_end_date."</td>
                                              </tr> ";
                                        }

                                      ?>
                                    </tbody>
                                 
                                </table>
        <hr>
        <br>
        <p style="font-size: 15px; margin-top:30px; margin-bottom: 20px">
          Report Generated By:<br><br><br>
          <i>Juan Dela Cruz</i> <br>
          <i>President</i>
        </p>
     </div>
     <!-- end panel-body -->
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#rlogo').append("<src='../../../resources/images/nvyc.png'/>");
  });
</script>