<!-- <link href="../../../resources/custom/print_format.css" media="print" rel="stylesheet" /> -->
<style type="text/css">
  @page {
    size:letter;
    margin-top: 0.7in; 
    margin-left: 0.7in;
    margin-right: 0.7in;
    margin-bottom: 0.7in;
   
  }
  hr {
     border: none; 
     border-bottom: 1px solid black;
  }
  table {
    border-collapse: collapse;
  }

  table, th, td {
    border: 1px solid black;
  }

  #rlogo {
    margin-left: 290px;
    width: 100px;
  }

</style>


<div style="display: none">
  <div id="sponsor" class="panel-body" style="color: black">
     <!-- begin panel-body -->
     <!--For Details-->
     
     <!--For Details-->
     <div class="panel" style="font-family: arial;">
        <!-- <p style="font-size: 14px; text-align: center">
           Republic of the Philippines<br>
           Province of Batangas<br>
           Municipality of Tuy<br>
        </p> -->
        <p><img id="rlogo" src="../../../resources/images/nvyc.png"></p>
        <p style="font-size: 16px; font-weight:bold; text-align: center; margin-top: 20px; margin-bottom: 40px">NATIONAL YOUTH VOLUNTEERS COALITION</p>
        <table>
          <tr>
            <td style="width: 480px;border-color: white">
              Date Created: <?php echo date('F d, Y')?>
            </td>
            <td style="width: 380px; text-align: right;border-color: white">
              Report No: SPONSOR<?php echo date('Ymd')?>
            </td>
          </tr>
        </table>
        <hr>
        <p style="font-size: 19px; font-weight:bold; text-align: center; margin-top: 20px">REPORT ON SPONSORS</p>
        <hr>

        <p style="font-size: 16px; text-align: justify">
          <b>Report Description:</b><br><br>
           &nbsp;&nbsp;&nbsp;
           This report contains the details of all sponsors of different events.
           <br>
           <!-- &nbsp;&nbsp;&nbsp;
           Details in this report may be filtered according to the specifications and preferences set by the report generator. -->
        </p>
         <p style="font-size: 16px; text-align: justify">
          <b>Table Description:</b><br><br>
           &nbsp;&nbsp;&nbsp;
           The table contains the following fields: sponsor name, type, contact number, and address.
           <br>

        </p>
        <table id="data-table" class="table table-striped table-bordered" width="100%">
                                    <thead>
                                        <tr>
                                          <th>Sponsor Name</th>
                                          <th>Type</th>
                                            <th>Contact No.</th>
                                            <th>Address</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                      <?php
                                      

                                        $query = "SELECT * FROM ems_r_sponsor AS S INNER JOIN ems_r_sponsor_type AS ST ON S.rs_stype_id = ST.rst_stype_id WHERE rs_status = 1";

                                        $runquery = mysqli_query($connection, $query);

                                        while ($row = mysqli_fetch_assoc($runquery)){

                                          $data_sponsor = $row['rs_sponsor_name'];
                                          $data_type = $row['rst_stype_name'];
                                          $data_conno = $row['rs_sponsor_contact_no'];
                                          $data_address = $row['rs_sponsor_address'];
                                          $datasponsorid = $row['rs_sponsor_id'];

                                          echo "<tr>
                                              <td>".$data_sponsor."</td>
                                              <td>".$data_type."</td>
                                              <td>".$data_conno."</td>
                                              <td>".$data_address."</td>
                                              </tr>";
                                          }

                                        ?>
                                      </tbody>
                                 
                                </table>
        <hr>
        <br>
        <p style="font-size: 15px; margin-top:30px; margin-bottom: 20px">
          Report Generated By:<br><br><br>
          <i>Juan Dela Cruz</i> <br>
          <i>President</i>
        </p>
     </div>
     <!-- end panel-body -->
  </div>
</div>